const double ATHENS_LONGITUDE = 23.7268;
const double ATHENS_LATITUDE = 37.9722;
const double ATHENS_ALTITUDE = 70;
const double ATHENS_MEAN_TEMPERATURE = 17.5;
const double ATHENS_MEAN_ATPRESSURE = 1013.25;
const double ATHENS_MEAN_HUMIDITY = 40.0;

double ATHENS_GEOPOS[3] = {ATHENS_LONGITUDE, ATHENS_LATITUDE, ATHENS_ALTITUDE};
double ATHENS_ATMOSPHERE[4] = {ATHENS_MEAN_ATPRESSURE, ATHENS_MEAN_TEMPERATURE, ATHENS_MEAN_HUMIDITY, 0};
